# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: da75e639b77aad449c1c698ae68b9974beb4af8d70df9a0fde93ee2797e8cbbdf314f83e4946734d64bec6035029a6b5c0c105dd82038a5e727ef45507b779e8

test:
  secret_key_base: 920abce543cb03f567b45f5279e35fcdb495a0b6daaf11fb181440e60b2ebaecbcf2ce57fbb212217724bb4581da5978a7016cdff080594713a8063d910c079e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
